version: '3'

services:
  # Next.js
  next:
    build: .
    container_name: next
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: production
      CATEIRU_SSO_CLIENT_ID: hogehoge
      CATEIRU_SSO_CLIENT_SECRET: hogehoge
