version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noratomo
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 4443:4443
    volumes:
      - ./.data:/data/noratomo:cached
      - ./.storage:/storage/noratomo
    environment:
      URL: ${URL:-localhost}
    command: -scheme http -public-host $URL:4443
