# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      
      - name: szenius/set-timezone@v1.0
        with: |
          - timezoneLinux: "Asia/Tokyo"
      
      - name: docker
        run: docker-compose up -d
      
      - name: yarn install
        run: yarn install --dev
        
      - name: Run test and linter
        run: yarn test
        
      - name: Build
        run: yarn build
